name: ros2

on:
  push:
    paths:
      - ".github/workflows/ros2.yml"
      - "l3xz_openmv_camera/**"
      - "l3xz_openmv_camera_interfaces/**"
      - "launch/**"
  pull_request:
    paths:
      - ".github/workflows/ros2.yml"
      - "l3xz_openmv_camera/**"
      - "l3xz_openmv_camera_interfaces/**"
      - "launch/**"

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build on ros2 ${{ matrix.ros_distro }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ros_distro: [ humble ]

    steps:   
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ matrix.ros_distro }}
    
    - name: Setup ros2 workspace
      run: | 
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        mkdir -p ${{github.workspace}}/ros2_ws/src
        cd ${{github.workspace}}/ros2_ws
        colcon build
        
    - uses: actions/checkout@v4
      with:
        path: 'ros2_ws/src/l3xz_openmv_camera'
        
    - name: colcon build
      run: |
        cd ${{github.workspace}}/ros2_ws/src/l3xz_openmv_camera
        git submodule update --init --progress --depth 1
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        cd ${{github.workspace}}/ros2_ws
        PYTHONWARNINGS=ignore:::setuptools.command.install,ignore:::setuptools.command.easy_install,ignore:::pkg_resources colcon build --packages-select l3xz_openmv_camera
